### ISSUE TITLE
[Bug] Robots don't work properly

### ISSUE THREAD

**Issue by Bia10** [alaestor/Rimworld-MiscRobotsPlusPlus#10]
- They don't haul things for construction
- They don't mine in quarry

i remember these things working pre 1.3 patch

**Comment by Commissar0617** [comment]
I have this issue as well. they don't craft things either.

**Comment by Codingale** [comment]
I have them mining in quarries and hauling for crafting, but I can't seem to get them to haul for construction.

**Comment by klllr** [comment]
My bulder/omni bots start working in quarry at 0h, and stop at exactly 1h.  Tried to limit their allowed area, tried to move their base stations as close to the quarry as possible, changed the mod load order (at first tried to load Quarry after Misc. Robots++, but then reordered it so it loads first). Zero effect. I don't really know C#, but I'll try to find the reason why it happens on the weekend.

**Comment by Codingale** [comment]
oh, I found a conflict a bit after posting that with work tab, for some reason it broke the schedule and kept me from having the robots haul, dunno if that'll help you though. Just an update.

**Comment by KeaneCarotenuto** [comment]
Installing "MiscRobots WorkTab support" fixed this issue for me.

**Comment by NovaZek** [comment]
Installing a mod to fix an issue on another isn't that wrong of an idea, but not in this case since the problem here is, that MiscRobots WorkTab Support will bug out Fluffy's Work Tab mod entirely, while it even requires that mod as prereq. You won't be able to scroll through pawns (rarely happening) nor through the robots (always present and bugging) work tabs.
